routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ===============================================
// ADMIN SECTION =================================
// ===============================================
Route::group(array('prefix' => 'admin'), function()
{
    // main page for the admin section (app/views/admin/dashboard.blade.php)
    Route::get('/', function()
    {
        return View::make('centaur.dashboard');
    });

    // subpage for the posts found at /admin/posts (app/views/admin/posts.blade.php)
    Route::get('posts', function()
    {
        return View::make('admin.posts');
    });

    // subpage to create a post found at /admin/posts/create (app/views/admin/posts-create.blade.php)
    Route::get('posts/create', function()
    {
        return View::make('admin.posts-create');
    });
});

Route::get('/', ['as' => 'top', 'uses' => 'TopController@index']);
Route::get('/error', ['as' => 'top.error', 'uses' => 'TopController@error']);
Route::get('/search', ['as' => 'search', 'uses' => 'TopController@search']);

// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Registration
Route::get('register', ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);
Route::get('notice', ['as' => 'notice', 'uses' => function() {
    return view('centaur.notice');
}]);


// Activation
Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

// Password Reset
Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);


Route::group(['middleware' => ['guest']], function() {
    Route::get('profile/{id}', ['as' => 'profile', 'uses' => 'TopController@getProfile' ]);
    Route::get('editprofile', ['as' => 'editprofile', 'uses' => 'TopController@editProfile' ]);
    Route::post('updateprofile', ['as' => 'updateprofile', 'uses' => 'TopController@updateProfile' ]);
    Route::get('my_lives', ['as' => 'my_lives', 'uses' => 'TopController@myLives' ]);

    // Users
    Route::resource('users', 'UserController');

    // Roles
    Route::resource('roles', 'RoleController');

    Route::get('/lives/publish/{id}', ['as' => 'lives.publish', 'uses' => 'LiveController@publish' ]);
    Route::get('/lives/un_publish/{id}', ['as' => 'lives.un_publish', 'uses' => 'LiveController@unPublish' ]);
    Route::get('/lives/display/{id}', ['as' => 'lives.display', 'uses' => 'LiveController@display' ]);

});


//// Single route
//Route::get('profile', function () {
//    // Only authenticated users may enter...
//})->middleware('auth');


// Dashboard
Route::get('dashboard', ['as' => 'dashboard', 'uses' => function() {
    return view('centaur.dashboard');
}]);

// Lessons
Route::resource('lessons', 'LessonController');

// Courses
Route::resource('courses','CourseController');

// Lives
Route::resource('lives', 'LiveController');

Route::post('/upload/video/{type}',array('as'=>'upload.video', 'before'=>'auth', 'uses'=>'UploadController@video'));
Route::post('/upload/image/{type}',array('as'=>'upload.image', 'before'=>'auth', 'uses'=>'UploadController@image'));

app/Http/Controllers/TopController.php
<?php

namespace App\Http\Controllers;

use App\Course;
use App\Lesson;
use App\Lib\AzureMediaService;
use App\Live;
use App\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Sentinel;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;

class TopController extends Controller
{
    /**
     * Top screen
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        // 新着の授業動画
        $lessons = Lesson::select('lessons.*', 'courses.title as course_title')
            ->leftJoin('courses', 'lessons.course_id', '=', 'courses.id')
            ->orderBy('lessons.id','DESC')
            ->get()
        ;

        $premiumUsers = User::where(['service_plan' => 'premium'])
            //->orderBy('count','DESC')
            ->limit(10)
            ->get()
        ;

        return view('top.index',compact('lessons','premiumUsers','categories'));
    }

    /**
     * Profile screen
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function getProfile(Request $request, $id){
        $user = User::find($id);

        if(!$user){
            return redirect()->route('top.error');
        }

        return view('top.profile', compact('user'));
    }

    /**
     * Edit profile screen (display)
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function editProfile(Request $request){
        $profile = Sentinel::getUser();
        return view('top.editprofile',compact('profile'));
    }

    /**
     * Edit profile screen (update)
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function updateProfile(Request $request){
        // Validate the form data
        if(!empty($request->input('password'))) {
            $result = $this->validate($request, [
                'password' => 'required',
                'password_retry' => 'required|min:6',
            ]);
        }
        $profile = Sentinel::getUser();
        $hashedPassword = $profile->password;
        $checked = false;
        if (Hash::check($request->password, $hashedPassword)) {
            $checked = true;
            // todo check validate
            $profile->password = Hash::make($request->password_retry);
        }else{
            $request->offsetUnset('password');
        }
        Sentinel::update($profile, $request->all());

        if(!empty($request->input('password_retry')) && $checked) {
                $profile->password = Hash::make($request->password_retry);
//                $new_password = bcrypt($request->input('password_retry'));
//                $profile->password = $new_password;
                $profile->save();
            }

        return view('top.profile');
    }

    /**
     * Search screen
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function search(Request $request){
        // Sets the parameters from the get request to the variables.
        $search = $request->get('keyword'); //<-- we use global request to get the param of URI

        $lessons = Lesson::with('users')->where('title','like','%'.$search.'%')
            ->orderBy('title')
            ->paginate(10);

        $courses = Course::with('users')->where('title','like','%'.$search.'%')
            ->orderBy('title')
            ->paginate(10);

        $categories = self::CATEGORIES;
        return view('top.search',compact('lessons','courses','categories'));
    }

    /**
     * My Lives function
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function myLives(Request $request){
        $user = Sentinel::getUser();
        if (!$user || $user->service_plan != 'premium') {
            return redirect()->route('auth.login.form');
        }

        $lives = Live::where(['user_id' => $user->getUserId()])->orderBy('id', 'DESC')->paginate(16);

        return view('top.my_lives', compact('lives'))
            ->with(['i' => ($request->input('page', 1) - 1) * 16]);
    }

    public function error(Request $request){
        return view('top.error');
    }
}

resources/views/top/error.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <!-- Slider -->
    <link rel="stylesheet" href="{{ asset('/css/slick.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/plugins/slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('/plugins/slick/slick-theme.css') }}"/>
    <!-- Alert -->
    <link href="{{ asset('/plugins/sweet-alert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('/plugins/custombox/css/custombox.css') }}" rel="stylesheet">
    <link href="{{ asset('/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/switchery/css/switchery.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/multiselect/css/multi-select.css') }}"  rel="stylesheet" type="text/css" />
    <link href="{{ asset('/plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/plugins/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/core.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/components.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/pages.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/responsive.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('plugins/sweet-alert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('/ju/css/jquery.fileupload.css') }}">
    <script src="{{ asset('js/modernizr.min.js') }}"></script>

</head>
<body>

<div class="account-pages"></div>
<div class="clearfix"></div>

<div class="wrapper-page">
    <div class="ex-page-content text-center">
        <div class="text-error"><span class="text-primary">4</span><span class="text-pink">0</span><span class="text-info">0</span></div>
        <h2>Bad Request</h2><br>
        <p class="text-muted">Your browser sent an invalid request</p>
        <br>
        <a class="btn btn-default waves-effect waves-light" href="index.html"> Return Home</a>

    </div>
</div>


<script>
    var resizefunc = [];
</script>
</body>
</html>

resources/views/top/index.blade.php
@extends('layout')

@section('title', 'トップ')
@section('content')
<!-- Start content -->
<div class="content">
    <div class="container top_page">
        <!--
            スライダー
        -->
        <ul class="slider center-item">
            <li><a href="description.php"><img class="slider_image_07 slider_image" src="{{ asset('images/webcampus_banner_07.png') }}"></a></li>
            <li><a href="https://gakko-plus.com/guide.php"><img class="slider_image_08 slider_image" src="{{ asset('images/webcampus_banner_08.png') }}"></a></li>
            <li><a href="https://gakko-plus.com/lecturer-app.php"><img class="slider_image_09 slider_image" src="{{ asset('images/webcampus_banner_09.png') }}"></a></li>
        </ul>
        <!--
            ライブ放送のスケジュール
        -->
        <div class="row top_content">
            <div class="col-sm-12">
                <h4 class="page-header header-title">ライブ放送のスケジュール</h4>
            </div>
        </div>

        <div class="row top_content">
            <ul class="slider center-item-content top_live_date_content">
                {{--@foreach($courses as $item)--}}
                {{--<li>--}}
                    {{--<div class="card-box widget-box-1 bg-white top_live_date_box">--}}
                        {{--<div class="image top_live_date_box_in">--}}
                            {{--<!-- <i class="fa fa-heart-o text-muted pull-right inform" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="動画の説明もしくはお気に入り登録"></i> -->--}}
                            {{--<img class="img-rounded cover" width="100%" src="{{ route('courses.show', ['id' => $item->id]) }}">--}}
                            {{--<p>2017年3月10日 20:00〜</p>--}}
                        {{--</div>--}}
                        {{--<h4 class="text-dark">動画タイトル</h4>--}}
                    {{--</div>--}}
                {{--</li>--}}
                {{--@endforeach--}}
            </ul>
        </div>


        <!--  新着の授業動画  -->
        <div class="row top_content">
            <div class="col-sm-12">
                <h4 class="page-header  header-title">新着の授業動画</h4>
            </div>
        </div>

        <div class="row top_content">
            <ul class="slider center-item-content">
                @foreach($lessons as $item)
                <li>
                    <a href="{{ route('lessons.show', ['id' => $item->id ]) }}">
                        <div class="card-box widget-box-1 bg-white new_movie_slider_box">
                        <div class="image">
                            <h2 class="text-primary text-center new_movie_slider_image">
                            <img class="img-rounded cover slider_img" width="100%" src="{{ $item->thumbnail ? asset('images/lessons/'. $item->thumbnail) : asset('images/courses/no-image.jpg') }}">
                            </h2>
                        </div>
                        <p class="text-muted new_movie_slider_time">
                            <span class="pull-right"><i class="fa ti-time text-primary m-r-5"></i>24:20 </span>
                        </p>
                        <h4 class="text-dark slider_movie_title">{{ $item->title }}</h4></div></a>
                </li>
                @endforeach
           </ul>
        </div>

        <!--
            再生回数の多い先生
        -->
        <div class="row top_content">
            <div class="col-sm-12">
                <h4 class="page-header  header-title">再生回数の多い先生</h4>
            </div>
        </div>
        <div class="row top_content">

            <!--
                <br><p class="text-center">準備中 ＜集計中＞</P>
            -->
            <ul class="slider center-item-content_teacher famous-teacher">
                @foreach($premiumUsers as $premiumUser)
                    <li>
                        <div class="card-box p-b-0 famous_teacher_box">
                            <a href="{{ route('profile', ['id' => $premiumUser->id ]) }}" class="center-block text-center text-dark">
                                <img src="{{ asset('images/avatar-1.jpg') }}" class="thumb-lg img-thumbnail img-circle" alt="">
                                <div class="h5 m-b-0 famous_teacher_name">
                                    <strong>{{ $premiumUser->first_name . $premiumUser->last_name }}</strong>
                                </div>
                            </a>
                            <p class="teacher_job">{{ $premiumUser->company }}</p>
                        </div>
                    </li>
                @endforeach
            </ul>

        </div>
        <!--
            ページ下記
        -->
        <div class="row top_content">
            <div class="col-sm-12">
                <h4 class="page-header  header-title">ニュース</h4>
            </div>
        </div>

        <div class="row news_content">
            <div class="col-lg-7 news_content_box">

            </div>

            <div class="col-lg-5 sns_content_box">
                <div class="card-box">
                    <h4 class="text-dark header-title m-t-0 m-b-30">SNS</h4>
                    <div class="fb-page" data-href="https://www.facebook.com/gakkoplus/" data-tabs="timeline" data-width="500" data-height="204" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/gakkoplus/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/gakkoplus/">ガッコウ＋</a></blockquote></div>

                    <p class="center-text"><iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2Fgakkoplus%2F&tabs=timeline&width=300&height=200&small_header=true&adapt_container_width=true&hide_cover=true&show_facepile=false&appId"
                        width="100%" height="200" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></p>

                </div>
            </div>
        </div>
        <!-- end row -->

    </div>
</div>
<!-- end col -->
@stop

resources/views/top/my_lives.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            <h4 class="page-title">
                生放送一覧
                <a class="btn btn-default pull-right" href="{{ route('lives.create') }}">生放送作成</a>
            </h4>
            <ol class="breadcrumb">
                <li><a href="{{ route('top') }}">ホーム</a></li>
                <li class="active">生放送一覧</li>
            </ol>
        </div>
    </div>

    <div class="row port">
        <div class="portfolioContainer" style="position: relative; height: 1176px;">
            @foreach ($lives as $live)
                <div class="col-sm-6 col-lg-3 col-md-4 webdesign illustrator">
                    <div class="gal-detail thumb">
                        <h5>開始: {{ $live->start_time }} </h5>
                        <h5>終了: {{ $live->end_time }}</h5>
                        <a href="{{ route('lives.show', ['id' => $live->id]) }}" class="image-popup" title="Screenshot-1">
                            <img src="{{ $live->image ? asset('images/lives/'. $live->image) : asset('images/lives/no-image.jpg') }}" class="thumb-img" alt="work-thumbnail" style="max-height: 80px;">
                        </a>
                        <h5>{{ $live->title }}</h5>
                    </div>
                </div>
            @endforeach
        </div>
        <div class="col-xs-12" >
            <div class="pull-right">
                {!! $lives->render() !!}
            </div>
        </div>
    </div>

@stop

resources/views/top/search.blade.php
@extends('layout')

@section('title', 'トップ')
@section('content')
<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <h4 class="page-title">検索結果</h4>
                </div>
            </div>

            {!! Form::open(['method'=>'GET','url'=>'search','class'=>'','role'=>'search'])  !!}
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="input-group m-t-10">
                        <input type="text" id="search" name="keyword" class="form-control input-lg" placeholder="">
                                    <span class="input-group-btn">
                                    <button type="submit" class="btn waves-effect waves-light btn-default btn-lg"><i class="fa fa-search m-r-5"></i> 検索</button>
                                    </span>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
            <div class="row">
                <div class="col-lg-12">
                    <div class="search-result-box m-t-40">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#home" data-toggle="tab" aria-expanded="true">
                                    <span class="visible-xs"><i class="fa fa-home"></i></span>
                                    <span class="hidden-xs"><b>講座</b> <span class="badge badge-primary m-l-10">{{ count($courses) }}</span></span>
                                </a>
                            </li>
                            <li class="">
                                <a href="#users" data-toggle="tab" aria-expanded="false">
                                    <span class="visible-xs"><i class="fa fa-user"></i></span>
                                    <span class="hidden-xs"><b>講師</b> <span class="badge badge-pink m-l-10">{{ count($lessons) }}</span> </span>
                                </a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="home">
                                <div class="row">
                                    <div class="col-md-12">
                                        @foreach($courses as $item)
                                        <div class="search-item">
                                            <img src="{{ $item->image ? asset('images/courses/'. $item->image) : asset('images/courses/no-image.jpg') }}" class="lecture_thumbnail">
                                            <h3 class="h5 font-600 m-b-5"><a href="{{ route('courses.show', ['id' => $item->id]) }}">{{ $item->title }}</a></h3>
                                            <div class="font-13 text-success m-b-10">
                                                {{ $cat = '' }}
                                                @if ($item->category)
                                                    @foreach(explode(',',$item->category) as $row)
                                                        @php  $cat .= $categories[$row] . ',' @endphp
                                                    @endforeach
                                                @endif
                                                更新日：{{ $item->created_at->format('Y年m月d日') }}  | 担当講師：{{ isset($item->user_id) ? $item->users[0]->username : "" }} | カテゴリー：{{ rtrim($cat,',')}}
                                            </div>
                                            <p>
                                                {!!  nl2br($item->overview)  !!}
                                            </p>
                                        </div>
                                        @endforeach
                                        <ul class="pagination pagination-split pull-right">
                                            {!! $courses->render() !!}
                                        </ul>

                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>

                            <!-- end All results tab -->

                            <!-- Users tab -->
                            <div class="tab-pane" id="users">

                                @foreach($lessons as $item)
                                <div class="search-item">
                                    <div class="media">
                                        <div class="media-left">
                                            <a href="#"> <img class="media-object img-circle" alt="64x64" src="{{ $item->thumbnail ? asset('images/lessons/'. $item->thumbnail) : asset('images/courses/no-image.jpg') }}" style="width: 64px; height: 64px;"> </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading"><a href="{{ route('lessons.show', ['id' => $item->id]) }}">{{ $item->title }}</a></h4>
                                            <p>
                                                <b>Career</b>
                                                <br/>
                                                <span><a href="#" class="text-muted">{{  isset($item->user_id) ? $item->users[0]->job: "" }}</a></span></p>
                                            <p>
                                                <b>My profile</b>
                                                <br/>
                                                <span class="text-muted">{{ isset($item->user_id) ? $item->users[0]->my_message : "" }}</span>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                                <ul class="pagination pagination-split pull-right">
                                    {!! $lessons->render() !!}
                                </ul>
                                <div class="clearfix"></div>
                            </div>
                            <!-- end Users tab -->

                        </div>
                    </div>
                </div>
            </div>


        </div> <!-- container -->

    </div> <!-- content -->

</div>


@stop