routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ===============================================
// ADMIN SECTION =================================
// ===============================================
Route::group(array('prefix' => 'admin'), function()
{
    // main page for the admin section (app/views/admin/dashboard.blade.php)
    Route::get('/', function()
    {
        return View::make('centaur.dashboard');
    });

    // subpage for the posts found at /admin/posts (app/views/admin/posts.blade.php)
    Route::get('posts', function()
    {
        return View::make('admin.posts');
    });

    // subpage to create a post found at /admin/posts/create (app/views/admin/posts-create.blade.php)
    Route::get('posts/create', function()
    {
        return View::make('admin.posts-create');
    });
});

Route::get('/', ['as' => 'top', 'uses' => 'TopController@index']);
Route::get('/error', ['as' => 'top.error', 'uses' => 'TopController@error']);
Route::get('/search', ['as' => 'search', 'uses' => 'TopController@search']);

// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Registration
Route::get('register', ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);
Route::get('notice', ['as' => 'notice', 'uses' => function() {
    return view('centaur.notice');
}]);


// Activation
Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

// Password Reset
Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);


Route::group(['middleware' => ['guest']], function() {
    Route::get('profile/{id}', ['as' => 'profile', 'uses' => 'TopController@getProfile' ]);
    Route::get('editprofile', ['as' => 'editprofile', 'uses' => 'TopController@editProfile' ]);
    Route::post('updateprofile', ['as' => 'updateprofile', 'uses' => 'TopController@updateProfile' ]);
    Route::get('my_lives', ['as' => 'my_lives', 'uses' => 'TopController@myLives' ]);

    // Users
    Route::resource('users', 'UserController');

    // Roles
    Route::resource('roles', 'RoleController');

    Route::get('/lives/publish/{id}', ['as' => 'lives.publish', 'uses' => 'LiveController@publish' ]);
    Route::get('/lives/un_publish/{id}', ['as' => 'lives.un_publish', 'uses' => 'LiveController@unPublish' ]);
    Route::get('/lives/display/{id}', ['as' => 'lives.display', 'uses' => 'LiveController@display' ]);

});


//// Single route
//Route::get('profile', function () {
//    // Only authenticated users may enter...
//})->middleware('auth');


// Dashboard
Route::get('dashboard', ['as' => 'dashboard', 'uses' => function() {
    return view('centaur.dashboard');
}]);

// Lessons
Route::resource('lessons', 'LessonController');

// Courses
Route::resource('courses','CourseController');

// Lives
Route::resource('lives', 'LiveController');

Route::post('/upload/video/{type}',array('as'=>'upload.video', 'before'=>'auth', 'uses'=>'UploadController@video'));
Route::post('/upload/image/{type}',array('as'=>'upload.image', 'before'=>'auth', 'uses'=>'UploadController@image'));

resources/views/layouts/footer.blade.php
<!-- jQuery  -->
<script src="{{ asset('/js/jquery.min.js') }}"></script>
<script src="{{ asset('/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/js/detect.js') }}"></script>
<script src="{{ asset('/js/fastclick.js') }}"></script>
<script src="{{ asset('/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('/js/jquery.blockUI.js') }}"></script>
<script src="{{ asset('/js/waves.js') }}"></script>
<script src="{{ asset('/js/wow.min.js') }}"></script>
<script src="{{ asset('/js/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('/js/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('/plugins/peity/jquery.peity.min.js') }}"></script>
<script src="{{ asset('/plugins/timepicker/bootstrap-timepicker.js') }}"></script>
<script src="{{ asset('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
<script src="{{ asset('/plugins/multiselect/js/jquery.multi-select.js') }}"></script>
<script src="{{ asset('/plugins/jquery-quicksearch/jquery.quicksearch.js') }}"></script>
<script src="{{ asset('/plugins/select2/js/select2.min.js') }}"></script>
<script src="{{ asset('/plugins/bootstrap-select/js/bootstrap-select.min.js') }}"></script>
<script src="{{ asset('/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js') }}"></script>
<script src="{{ asset('/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js') }}"></script>
<script src="{{ asset('/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js') }}"></script>
<script src="{{ asset('/ju/js/vendor/jquery.ui.widget.js') }}"></script>
<script src="{{ asset('/ju/js/jquery.iframe-transport.js') }}"></script>
<script src="{{ asset('/ju/js/jquery.fileupload.js') }}"></script>
<script src="{{ asset('/js/jquery.core.js') }}"></script>
<script src="{{ asset('/plugins/waypoints/lib/jquery.waypoints.js') }}"></script>
<script src="{{ asset('/plugins/counterup/jquery.counterup.min.js') }}"></script>
{{--<script src="{{ asset('/plugins/morris/morris.min.js') }}"></script>--}}
<script src="{{ asset('/plugins/raphael/raphael-min.js') }}"></script>
<script src="{{ asset('/plugins/jquery-knob/jquery.knob.js') }}"></script>
{{--<script src="{{ asset('/pages/jquery.dashboard.js') }}"></script>--}}
<script type="text/javascript" src="{{ asset('/plugins/slick/slick.min.js') }}"></script>
<script src="{{ asset('/js/jquery.app.js') }}"></script>
<script src="{{ asset('/pages/jquery.form-advanced.init.js') }}"></script>
{{--<script src="{{ asset('/pages/jquery.form-pickers.init.js') }}"></script>--}}
<!--Modal-Effect-->
<script src="{{ asset('/plugins/custombox/js/custombox.min.js') }}"></script>
<script src="{{ asset('/plugins/custombox/js/legacy.min.js') }}"></script>
<!--Sweet-Alert-->
<script src="{{ asset('/plugins/sweet-alert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('/pages/jquery.sweet-alert2.init.js') }}"></script>

<script src="{{ asset('/gakko.js') }}"></script>
@yield('script')

resources/views/layouts/header.blade.php
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@yield('title')</title>
    <!-- Slider -->
    <link rel="stylesheet" href="{{ asset('/css/slick.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('/plugins/slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('/plugins/slick/slick-theme.css') }}"/>
    <!-- Alert -->
    <link href="{{ asset('/plugins/sweet-alert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('/plugins/custombox/css/custombox.css') }}" rel="stylesheet">
    <link href="{{ asset('/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/switchery/css/switchery.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/multiselect/css/multi-select.css') }}"  rel="stylesheet" type="text/css" />
    <link href="{{ asset('/plugins/select2/css/select2.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('/plugins/bootstrap-select/css/bootstrap-select.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('/plugins/timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/core.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/components.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/icons.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/pages.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('css/responsive.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('plugins/sweet-alert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{{ asset('/ju/css/jquery.fileupload.css') }}">
    <script src="{{ asset('js/modernizr.min.js') }}"></script>
    @yield('css')
</head>

resources/views/layouts/leftmenu.blade.php
<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <div id="sidebar-menu">
            <ul>
                <li class="text-muted menu-title">Navigation</li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-home"></i> <span> ホーム </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled">
                        <li><a href="{{route('top')}}">トップ</a></li>
                        <li><a href="guide.php">使い方ガイド</a></li>
                        <li><a href="/">ガッコウ＋とは？</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="{{ route('courses.index') }}" class="waves-effect"><i class="ti-menu-alt"></i> <span> 講座一覧 </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <!-- <li><a href="live-calendar.php">生放送カレンダー</a></li> -->
                        @php ($categories = \App\Http\Controllers\CourseController::CATEGORIES)
                        @foreach($categories as $no=>$category)
                            <li><a href="{{ route('courses.index', ['category' => $no]) }}">{{ $category }}</a></li>
                        @endforeach
                    </ul>
                </li>
                @if (Sentinel::check())
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="icon-emotsmile"></i> <span> マイページ </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" >
                        <li><a href="{{route('profile', ['id' => Sentinel::getUser()->getUserId()])}}"> プロフィール</a></li>
                        <li><a href="{{route('editprofile')}}"> 個人設定</a></li>
                        <li><a href="{{ route('auth.logout') }}">ログアウト</a></li>
                    </ul>
                </li>
                @endif
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="md-movie"></i> <span> 動画の管理 </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" >
                        <li class="active"><a href="{{ route('lessons.index') }}" class="active">講座・授業の一覧</a></li>
                        <li><a href="{{ route('lessons.create') }}">授業の投稿</a></li>
                        @if (Sentinel::check())
                            @php($user = Sentinel::getUser())
                            @if($user['service_plan'] == 'premium')
                                <li><a href="{{ route('my_lives') }}">生放送一覧</a></li>
                            @endif
                        @endif
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="md-note-add"></i> <span> コンテンツの管理 </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled" >
                        <li><a href="#">ブログ</a></li>
                        <li><a href="#">ショップ</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-files"></i> <span> その他 </span> <span class="menu-arrow"></span></a>
                    <ul class="list-unstyled">
                        <li><a href="faq.php">よくある質問</a></li>
                        <li><a href="company.php">運営会社</a></li>
                        <li><a href="#">お問い合わせ</a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</div>

resources/views/layouts/topmenu.blade.php
<div class="topbar">
    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="{{ route('top') }}" class="logo">
                <i class="icon-c-logo"><img src="{{ asset('images/logo_sm.png') }}" height="42"/></i>
                <span><img src="{{ asset('images/logo_light.png') }}" width="120"/></span>
            </a>
        </div>
    </div>
    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="pull-left">
                <button class="button-menu-mobile open-left waves-effect waves-light">
                    <i class="md md-menu"></i>
                </button>
                <span class="clearfix"></span>
            </div>
            <form action="{{ route('search') }}" method="get" role="search" class="navbar-left app-search pull-left hidden-xs">
                <input type="text" name="keyword" placeholder="講座/授業を検索する" class="form-control">
                {{--<a href="/search"><i class="fa fa-search"></i></a>--}}
                <button type="submit" style="position: absolute;top: 3px;right: 10px;color: #c4c4cd; border:none; background: transparent"><i class="fa fa-search"></i></button>
            </form>

            @if (Sentinel::check())
                <ul class="nav navbar-nav navbar-right pull-right">
                    <li class="dropdown top-menu-item-xs">
                    </li>
                    <!-- Full Screen -->
                    <li class="hidden-xs">
                        <a href="#" id="btn-fullscreen" class="waves-effect waves-light"><i class="icon-size-fullscreen"></i></a>
                    </li>
                    <!-- Icon Menu -->
                    <li class="dropdown top-menu-item-xs">
                        <a href="" class="dropdown-toggle profile waves-effect waves-light" data-toggle="dropdown" aria-expanded="true">
                            <img src="{{ asset('images/users/avatar-1.jpg') }}" alt="user-img" class="img-circle"> </a>
                        <ul class="dropdown-menu">
                            <li><a href="{{route('profile', ['id' => Sentinel::getUser()->getUserId()])}}"><i class="ti-user m-r-10 text-custom"></i> プロフィール</a></li>
                            <li><a href="{{route('editprofile')}}"><i class="ti-settings m-r-10 text-custom"></i> 個人設定</a></li>
                            <li class="divider"></li>
                            <li><a href="{{route('auth.logout')}}"><i class="ti-power-off m-r-10 text-danger"></i> ログアウト</a></li>
                        </ul>
                    </li>
                    <!-- -->
                </ul>
            @else
                <div class="pull-right">
                    <a href="{{ route('auth.login.form') }}" class="btn btn-pink btn-custom btn-rounded waves-effect waves-light btn-middle">ログイン</a>
                    <a href="{{ route('auth.register.form')}}" class="btn btn-primary btn-custom btn-rounded waves-effect waves-light btn-middle">会員登録</a>
                </div>
            @endif
        </div>
    </div>
</div>