routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ===============================================
// ADMIN SECTION =================================
// ===============================================
Route::group(array('prefix' => 'admin'), function()
{
    // main page for the admin section (app/views/admin/dashboard.blade.php)
    Route::get('/', function()
    {
        return View::make('centaur.dashboard');
    });

    // subpage for the posts found at /admin/posts (app/views/admin/posts.blade.php)
    Route::get('posts', function()
    {
        return View::make('admin.posts');
    });

    // subpage to create a post found at /admin/posts/create (app/views/admin/posts-create.blade.php)
    Route::get('posts/create', function()
    {
        return View::make('admin.posts-create');
    });
});

Route::get('/', ['as' => 'top', 'uses' => 'TopController@index']);
Route::get('/error', ['as' => 'top.error', 'uses' => 'TopController@error']);
Route::get('/search', ['as' => 'search', 'uses' => 'TopController@search']);

// Authorization
Route::get('/login', ['as' => 'auth.login.form', 'uses' => 'Auth\SessionController@getLogin']);
Route::post('/login', ['as' => 'auth.login.attempt', 'uses' => 'Auth\SessionController@postLogin']);
Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\SessionController@getLogout']);

// Registration
Route::get('register', ['as' => 'auth.register.form', 'uses' => 'Auth\RegistrationController@getRegister']);
Route::post('register', ['as' => 'auth.register.attempt', 'uses' => 'Auth\RegistrationController@postRegister']);
Route::get('notice', ['as' => 'notice', 'uses' => function() {
    return view('centaur.notice');
}]);


// Activation
Route::get('activate/{code}', ['as' => 'auth.activation.attempt', 'uses' => 'Auth\RegistrationController@getActivate']);
Route::get('resend', ['as' => 'auth.activation.request', 'uses' => 'Auth\RegistrationController@getResend']);
Route::post('resend', ['as' => 'auth.activation.resend', 'uses' => 'Auth\RegistrationController@postResend']);

// Password Reset
Route::get('password/reset/{code}', ['as' => 'auth.password.reset.form', 'uses' => 'Auth\PasswordController@getReset']);
Route::post('password/reset/{code}', ['as' => 'auth.password.reset.attempt', 'uses' => 'Auth\PasswordController@postReset']);
Route::get('password/reset', ['as' => 'auth.password.request.form', 'uses' => 'Auth\PasswordController@getRequest']);
Route::post('password/reset', ['as' => 'auth.password.request.attempt', 'uses' => 'Auth\PasswordController@postRequest']);


Route::group(['middleware' => ['guest']], function() {
    Route::get('profile/{id}', ['as' => 'profile', 'uses' => 'TopController@getProfile' ]);
    Route::get('editprofile', ['as' => 'editprofile', 'uses' => 'TopController@editProfile' ]);
    Route::post('updateprofile', ['as' => 'updateprofile', 'uses' => 'TopController@updateProfile' ]);
    Route::get('my_lives', ['as' => 'my_lives', 'uses' => 'TopController@myLives' ]);

    // Users
    Route::resource('users', 'UserController');

    // Roles
    Route::resource('roles', 'RoleController');

    Route::get('/lives/publish/{id}', ['as' => 'lives.publish', 'uses' => 'LiveController@publish' ]);
    Route::get('/lives/un_publish/{id}', ['as' => 'lives.un_publish', 'uses' => 'LiveController@unPublish' ]);
    Route::get('/lives/display/{id}', ['as' => 'lives.display', 'uses' => 'LiveController@display' ]);

});


//// Single route
//Route::get('profile', function () {
//    // Only authenticated users may enter...
//})->middleware('auth');


// Dashboard
Route::get('dashboard', ['as' => 'dashboard', 'uses' => function() {
    return view('centaur.dashboard');
}]);

// Lessons
Route::resource('lessons', 'LessonController');

// Courses
Route::resource('courses','CourseController');

// Lives
Route::resource('lives', 'LiveController');

Route::post('/upload/video/{type}',array('as'=>'upload.video', 'before'=>'auth', 'uses'=>'UploadController@video'));
Route::post('/upload/image/{type}',array('as'=>'upload.image', 'before'=>'auth', 'uses'=>'UploadController@image'));

resources/views/courses/create.blade.php
@extends('layout')
@section('content')
    <div class="wraper container">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header-2">
                    <h4 class="page-title">講座・授業の管理</h4>
                    <ol class="breadcrumb">
                        <li class="active">
                            自身が投稿した講座・授業の作成から編集、また授業の公開・非公開設定等が可能です。
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-lg-12">
                            <h5><b></b></h5>
                            <p class="text-muted font-13 m-b-30">
                            </p>
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            {!! Form::open(array('route' => 'courses.store','method'=>'POST','files' => true,'class'=>"form-horizontal group-border-dashed")) !!}
                                <div class="form-group has-feedback">
                                    <label class="col-sm-3 control-label">講座名</label>
                                    <div class="col-sm-7">
                                        {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control inputmask','id' => "classname")) !!}
                                        <span class="glyphicon form-control-feedback"></span>
                                    </div>
                                </div>

                                <div class="form-group has-feedback">
                                    <label class="col-sm-3 control-label">講座概要</label>
                                    <div class="col-sm-7">
                                        {!! Form::textarea('overview', null, array('placeholder' => 'Overview','class' => 'form-control inputmask','id' => "gaiyou")) !!}
                                        <span class="glyphicon form-control-feedback"></span>
                                    </div>
                                </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label">サムネイル</label>
                                <div class="col-sm-7">
                                    <input id="imageUpload" type="file" name="file" data-url="{{ route('upload.image', ['type'=> 'courses'])  }}" accept='image/*'>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"></label>
                                <div class="col-sm-7">
                                    <!-- The container for the uploaded files -->
                                    <div id="display_name"></div>
                                    <input type="hidden" id="image" name="image" value=""/>

                                    <!-- The global progress bar -->
                                    <div id="progress" class="progress">
                                        <div class="progress-bar progress-bar-success"></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                    <div class="col-sm-3"></div>
                                    <div id="course_imagebox" class="col-sm-7"></div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">カテゴリー</label>
                                <div class="col-sm-7">
                                    @foreach ($categories as  $slug => $value)
                                        <div class="checkbox">
                                            <input tabindex="1" type="checkbox" name="category[]" id="category{{$slug}}" value="{{$slug}}">
                                            <label for="checkbox{{$slug}}">
                                                        {!! Form::label('category', $value) !!}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                            <div class="form-group m-b-0">
                                <div class="col-sm-offset-3 col-sm-9 m-t-15">
                                    <button type="submit" class="btn btn-primary" id="classup">
                                        保存
                                    </button>
                                </div>
                            </div>
                            {!! Form::close() !!}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('/js/pages/create_course.js') }}"></script>
@stop

resources/views/courses/edit.blade.php
@extends('layout')
@section('content')
    <div class="wraper container">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-header-2">
                    <h4 class="page-title">講座・授業の管理</h4>
                    <ol class="breadcrumb">
                        <li class="active">
                            自身が投稿した講座・授業の作成から編集、また授業の公開・非公開設定等が可能です。
                        </li>
                    </ol>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="card-box">
                    <div class="row">
                        <div class="col-lg-12">
                            <h5><b></b></h5>
                            <p class="text-muted font-13 m-b-30">
                            </p>
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            {!! Form::model($course, ['method' => 'PATCH','files' => true,'class'=>"form-horizontal group-border-dashed",'route' => ['courses.update', $course->id]]) !!}

                            <div class="form-group has-feedback">
                                <label class="col-sm-3 control-label">講座名</label>
                                <div class="col-sm-7">
                                    {!! Form::text('title', null, array('placeholder' => 'Title','class' => 'form-control inputmask','id' => "title")) !!}
                                    <span class="glyphicon form-control-feedback"></span>
                                </div>
                            </div>

                            <div class="form-group has-feedback">
                                <label class="col-sm-3 control-label">講座概要</label>
                                <div class="col-sm-7">
                                    {!! Form::textarea('overview', null, array('placeholder' => 'Overview','class' => 'form-control inputmask','id' => "overview")) !!}
                                    <span class="glyphicon form-control-feedback"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label">サムネイル</label>
                                <div class="col-sm-7">
                                    {{--{!! Form::file('image', null, array('placeholder' => 'jpg,png','class' => 'form-control filestyle', 'data-icon'=>"false",'data-buttonname'=>"btn-white" ,'id'=>"ss")) !!}--}}
                                    <input id="imageUpload" type="file" name="file" data-url="{{ route('upload.image', ['type'=> 'courses']) }}">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"></label>
                                <div class="col-sm-7">
                                    <!-- The container for the uploaded files -->
                                    <div id="display_name"></div>
                                    <input type="hidden" id="image" name="image" value=""/>

                                    <!-- The global progress bar -->
                                    <div id="progress" class="progress">
                                        <div class="progress-bar progress-bar-success"></div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-3"></div>
                                <div id="course_imagebox" class="col-sm-7"></div>
                            </div>

                            <div class="form-group">
                                <label class="col-sm-3 control-label">カテゴリー</label>
                                <div class="col-sm-7">
                                    @foreach ($categories as  $slug => $value)
                                        <div class="checkbox">
                                            <input tabindex="1" type="checkbox" name="category[]" id="category{{$slug}}"  {{ isset($course->category) && in_array($slug,  preg_split("/[\s,]+/", $course->category)) ? 'checked' : ''  }} value="{{$slug}}">
                                            <label for="checkbox{{$slug}}">
                                                {!! Form::label('category', $value) !!}
                                            </label>
                                        </div>
                                    @endforeach
                                </div>
                            </div>

                            <div class="form-group m-b-0">
                                <div class="col-sm-offset-3 col-sm-9 m-t-15">
                                    <button type="submit" class="btn btn-primary" id="btnsubmit">
                                        保存
                                    </button>
                                </div>
                            </div>
                            {!! Form::close() !!}

                            <br><hr><br>
                            <div class="row port">
                                <div class="portfolioContainer" style="position: relative;">
                                    @foreach ($lessons as $lesson)
                                        <div class="col-sm-6 col-lg-3 col-md-4 webdesign illustrator">
                                            <div class="gal-detail thumb">
                                                <a href="{{ route('lessons.show', ['id' => $lesson->id]) }}" class="image-popup" title="Screenshot-1">
                                                    <img src="{{ $lesson->thumbnail ? asset('images/lesson/'. $lesson->thumbnail) : asset('images/lesson/no-image.jpg') }}" class="thumb-img" alt="work-thumbnail">
                                                </a>
                                                <h4>{{ $lesson->title }}</h4>
                                            </div>
                                        </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('/js/pages/create_course.js') }}"></script>
@stop

resources/views/courses/index.blade.php
@extends('layout')
@section('content')
    <div class="row">
        <div class="col-sm-12">
            {{--<div class="btn-group pull-right m-t-15">--}}
                {{--<button type="button" class="btn btn-default dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">講座作成 --}}
                    {{--<span class="m-l-5"><i class="fa fa-cog"></i></span>--}}
                {{--</button>--}}
                {{--<ul class="dropdown-menu drop-menu-right" role="menu">--}}
                    {{--<li><a href="#">Action</a></li>--}}
                    {{--<li><a href="#">Another action</a></li>--}}
                    {{--<li><a href="#">Something else here</a></li>--}}
                    {{--<li class="divider"></li>--}}
                    {{--<li><a href="#">Separated link</a></li>--}}
                {{--</ul>--}}
            {{--</div>--}}

            <h4 class="page-title">
                講座一覧
                @if(Sentinel::check())
                    @php($user = Sentinel::getUser())
                    @if($user['service_plan'] == 'premium')
                        <a class="btn btn-primary pull-right" href="{{ route('courses.create') }}"> 講座作成</a>
                    @endif
                @endif
            </h4>
            <ol class="breadcrumb">
                <li><a href="{{ route('top') }}">ホーム</a></li>
                <li class="active">講座一覧</li>
            </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 ">
            <div class="portfolioFilter">
                <a href="{{route('courses.index')}}" data-filter="*" class="{{ $categoryNo == '' ? 'current' : '' }}">All</a>
                @foreach($categories as $no=>$category)
                    <a href="{{ route('courses.index', ['category' => $no]) }}" class="{{ $categoryNo == $no ? 'current' : '' }}">{{ $category }}</a>
                @endforeach
            </div>
        </div>
    </div>

    <div class="row port">
        <div class="portfolioContainer" style="position: relative; height: 1176px;">
            @foreach ($courses as $course)
            <div class="col-sm-6 col-lg-3 col-md-4 webdesign illustrator">
                <div class="gal-detail thumb">
                    <a href="{{ route('courses.show', ['id' => $course->id]) }}" class="image-popup" title="Screenshot-1">
                        <img src="{{ $course->image ? asset('images/courses/'. $course->image) : asset('images/courses/no-image.jpg') }}" class="thumb-img" alt="work-thumbnail">
                    </a>
                    <h4>{{ $course->title }}</h4>
                </div>
            </div>
            @endforeach
        </div>
        <div class="col-xs-12" >
            <div class="pull-right">
                {!! $courses->render() !!}
            </div>
        </div>
    </div>

@stop

resources/views/courses/show.blade.php
@extends('layout')
@section('content')
    <div class="card-box" style="overflow: auto">
        <div class="col-xs-12" style="margin-bottom: 10px">
            <h3 class="panel-title">
                {{ $course->title }}
            </h3>
            <small>カテゴリ: {{ implode(', ', $categoryNames) }}</small>

            @php ($user = Sentinel::getUser())
            @if ($user['service_plan'] == 'premium')
            <div class="btn-group pull-right">
                <a href="{{route('courses.edit', ['id' => $course['id'] ])}}" class="btn btn-sm btn-primary waves-effect waves-light">編集<span class="m-l-5"><i class="fa fa-cog"></i></span>
                </a>
            </div>
            @endif
        </div>

        <div class="col-xs-8">
            <img src="{{ $course['image'] ? asset('images/courses/' . $course['image']) :  asset('images/courses/no-image.jpg')}}" width="400px" height="200px">
        </div>

        <div class="col-lg-4">
            <div class="panel panel-border panel-custom">
                <div class="panel-heading">
                    <h3 class="panel-title">次回の生放送</h3>
                </div>
                <div class="panel-body">
                    <p>
                        8月２２日
                    </p>
                    <p>
                        10時 ~ 15時
                    </p>
                </div>
            </div>
        </div>

        <div class="col-xs-12">
            <p>
                {!! nl2br($course->overview) !!}
            </p>
        </div>
    </div>

    <div class="card-box">
        <h3 class="panel-title">授業一覧</h3>
        <div class="col-xs-12 ">
            <div class="row port">
                <div class="portfolioContainer" style="position: relative;">
                    @foreach ($lessons as $lesson)
                        <div class="col-sm-6 col-lg-3 col-md-4 webdesign illustrator">
                            <div class="gal-detail thumb">
                                <a href="{{ route('lessons.show', ['id' => $lesson->id]) }}" class="image-popup" title="Screenshot-1">
                                    <img src="{{ $lesson->thumbnail ? asset('images/lessons/'. $lesson->thumbnail) : asset('images/lesson/no-image.jpg') }}" class="thumb-img" alt="work-thumbnail">
                                </a>
                                <h4>{{ $lesson->title }}</h4>
                            </div>
                        </div>
                    @endforeach
                    <p>
                    </p>
                </div>
            </div>
        </div>
    </div>
@stop